// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuLoQip9bzO_xgwN3YQOx2fJ57qwwVpg8',
    appId: '1:1000172025245:web:a42a5d77e7db4dde09ab74',
    messagingSenderId: '1000172025245',
    projectId: 'salespurchaseproject',
    authDomain: 'salespurchaseproject.firebaseapp.com',
    storageBucket: 'salespurchaseproject.firebasestorage.app',
    measurementId: 'G-MEPBWJ1EN2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDemY9l4mLOrMaIbhWWMlnxNea7NEMCd50',
    appId: '1:1000172025245:android:8e2d55864804cd1809ab74',
    messagingSenderId: '1000172025245',
    projectId: 'salespurchaseproject',
    storageBucket: 'salespurchaseproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUryl9b_6Ztw9Q29JrEVaJAcWmDLNw0lU',
    appId: '1:1000172025245:ios:2327c48d03784c0609ab74',
    messagingSenderId: '1000172025245',
    projectId: 'salespurchaseproject',
    storageBucket: 'salespurchaseproject.firebasestorage.app',
    iosBundleId: 'com.example.inwardOutwardManagement',
  );
}
